### ISSUE TITLE
Third party number systems

### ISSUE THREAD

**Issue by Ang2Tea** [fizzyizzy05/binary#13]
I have a question: will there be support for other number systems?
For example
- Duodecimal;
- Decadimal;
- and so on.

**Comment by Ang2Tea** [comment]
It would be cool if they appeared, I can help with the calculation logic, but not with the visuals

**Comment by fizzyizzy05** [comment]
So it's definitely possible, but it'd need both code and UX design.

Currently, Binary is designed to accommodate specific bases calculations, and every time a new base is added, there's more calculations to do and test for, so it's easier to develop and test for the 4 main ones that are used. From a code standpoint, this would mean rewriting (from scratch, pretty much) how calculations are actually performed, and making sure it won't break with an infinite number of bases. Also, I'm trying to keep the UX of Binary simple and I feel like adding in support for custom bases would make that a lot more complicated

I could add select additional bases depending on how much users want them, but again it does add additional testing to do every time that's changed. Again, I'm not strictly opposed, but it'd be a lot of work and refactoring, and still have more testing to do in the end. I also have other things I want to do as well that are higher priority right now.

This is very much a long winded way of saying that I like the idea, but it's a lot of work and not the highest priority right now. If you want to work on it ofc, I don't really mind, just keep this in mind.

**Comment by Ang2Tea** [comment]
On my phone I use this [app](https://play.google.com/store/apps/details?id=ru.sandello.binaryconverter).
Perhaps it will help inspire your design.

I can help with the conversion logic, but I don't know how to design. I'll try to look at the project and figure out where to fit the logic.

**Comment by fizzyizzy05** [comment]
Fixed in #19
