### ISSUE TITLE
Feature: Only show active bits

### ISSUE THREAD

**Issue by eyekay-gh** [fizzyizzy05/binary#16]
Hi, I think the 'bits' dropdown when a binary number is entered should only show which bits are active. For example, for 10110, it would show 16, 4, 2.

I think this is more useful than showing all the bits in the number, because once you know the most significant bit's value, the rest are just the lesser powers of two. If it only shows the active bits, I can figure out the decimal of the number quickly even if I am actually converting it to some other base.

**Comment by fizzyizzy05** [comment]
the bit counter should look something like this now 
![image](https://github.com/user-attachments/assets/0268f10f-c55a-4a23-a3b2-2066aaa44ab1)
