### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [fizzyizzy05/binary#2]
The current summary "Number base converter, written in Python with GTK/Libadwaita" is longer than the recommended maximum (35 chars), and should not include technical detail like the toolkit. How about just "Number base converter"?

Appdata quality guidelines: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/

**Comment by fizzyizzy05** [comment]
Hi, thank you for taking a look and for the suggestion. I've just updated it to just "Number base converter" for 0.1.3. See commit [5ca0155](https://github.com/fizzyizzy05/binary/commit/5ca0155f64fce7baaf394ee5e2c74726916217ae).
