### ISSUE TITLE
Use `AdwAboutDialog`

### ISSUE THREAD

**Issue by bragefuglseth** [fizzyizzy05/binary#27]
While the app window *is* quite small, I think `AdwAboutDialog` has enough advantages over `AdwAboutWindow` both in adaptiveness and consistency to be worth it. The about window also currently covers the entire app, which might lead people to wonder where the app itself went. We'd avoid that with the about dialog.

**Comment by fizzyizzy05** [comment]
Done. I've increased the window height slightly so it doesn't look as bad, although I'm not sure I love this design.
![image](https://github.com/user-attachments/assets/e48f3968-7dab-48da-a46d-a3534f71aec7)
